export interface Concern {
  id: string;
  name: string;
  slug: string;
  description: string;
  icon: string;
  image: string;
  tips: string[];
  color: string;
}

export const concerns: Concern[] = [
  {
    id: "con-1",
    name: "Immunity Booster",
    slug: "immunity-booster",
    description: "Strengthen your body's natural defense system with time-tested Ayurvedic herbs and formulations. Build resilience from within using the wisdom of ancient medicine.",
    icon: "Shield",
    image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400&h=300&fit=crop",
    tips: [
      "Start your day with warm water and honey",
      "Include Amla and Tulsi in your daily diet",
      "Practice Pranayama (breathing exercises) daily",
      "Get 7-8 hours of quality sleep",
      "Consume Chyawanprash regularly during season changes",
    ],
    color: "#1F5D3B",
  },
  {
    id: "con-2",
    name: "Digestive Care",
    slug: "digestive-care",
    description: "Ayurveda considers digestion (Agni) as the cornerstone of health. Support your digestive fire with natural herbs that promote healthy gut function and regularity.",
    icon: "Flame",
    image: "/productimages/Yakirattan.jpeg",
    tips: [
      "Eat meals at regular times every day",
      "Chew food thoroughly — at least 32 times",
      "Drink warm water between meals",
      "Avoid cold drinks during meals",
      "Take a short walk after dinner",
    ],
    color: "#C9A961",
  },
  {
    id: "con-3",
    name: "Diabetic Care",
    slug: "diabetic-care",
    description: "Manage blood sugar levels naturally with Ayurvedic herbs known for their glucose-regulating properties. Support your pancreatic health the natural way.",
    icon: "Activity",
    image: "https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400&h=300&fit=crop",
    tips: [
      "Include bitter foods like Karela in your diet",
      "Walk at least 30 minutes daily after meals",
      "Reduce refined carbohydrates and sugar",
      "Consume Methi (Fenugreek) soaked water in the morning",
      "Monitor blood sugar levels regularly",
    ],
    color: "#2D6A47",
  },
  {
    id: "con-4",
    name: "Cardiac Care",
    slug: "cardiac-care",
    description: "Support your heart health with Ayurvedic herbs like Arjuna that have been used for millennia. Maintain healthy blood pressure and cholesterol levels naturally.",
    icon: "Heart",
    image: "https://images.unsplash.com/photo-1544991875-5dc1b05f607d?w=400&h=300&fit=crop",
    tips: [
      "Practice daily meditation for stress management",
      "Include garlic and turmeric in your diet",
      "Exercise moderately for 30 minutes daily",
      "Limit salt and processed food intake",
      "Consume Arjuna bark tea regularly",
    ],
    color: "#004526",
  },
  {
    id: "con-5",
    name: "Pain Relief",
    slug: "pain-relief",
    description: "Find natural relief from joint pain, body aches, and inflammation with potent Ayurvedic oils and formulations that address the root cause.",
    icon: "Zap",
    image: "https://images.unsplash.com/photo-1600428877878-1a0ff561972c?w=400&h=300&fit=crop",
    tips: [
      "Apply warm Mahanarayan oil on affected joints",
      "Practice gentle yoga daily",
      "Include anti-inflammatory spices like Turmeric and Ginger",
      "Stay hydrated throughout the day",
      "Maintain a healthy body weight",
    ],
    color: "#5A4302",
  },
  {
    id: "con-6",
    name: "Men's Health",
    slug: "mens-health",
    description: "Enhance masculine vitality, strength, and overall wellness with Ayurvedic rasayanas and tonics specifically formulated for men's health needs.",
    icon: "Dumbbell",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=300&fit=crop",
    tips: [
      "Consume Ashwagandha regularly for stress management",
      "Exercise consistently — both cardio and strength",
      "Get adequate protein in your diet",
      "Maintain a consistent sleep schedule",
      "Include Shilajit and Safed Musli for vitality",
    ],
    color: "#1F5D3B",
  },
  {
    id: "con-7",
    name: "Cough & Cold Relief",
    slug: "cough-cold-relief",
    description: "Daily respiratory support with traditional syrups, kadhas, drops, and herbal powders for seasonal wellness.",
    icon: "Wind",
    image: "/productimages/KuffRattan_syrup.jpeg",
    tips: [
      "Sip warm water through the day",
      "Avoid cold drinks during seasonal changes",
      "Use steam inhalation when congested",
      "Keep sleep and meal timings consistent",
      "Consult a practitioner for persistent symptoms",
    ],
    color: "#2D6A47",
  },
  {
    id: "con-8",
    name: "Elderly Care",
    slug: "elderly-care",
    description: "Gentle Ayurvedic support for digestion, joints, vitality, urinary comfort, and everyday wellness in later years.",
    icon: "Users",
    image: "/productimages/Badam_pak.jpeg",
    tips: [
      "Prefer warm, easy-to-digest meals",
      "Keep light movement in the daily routine",
      "Hydrate regularly",
      "Support sleep with calm evening habits",
      "Review chronic concerns with a doctor",
    ],
    color: "#5A4302",
  },
  {
    id: "con-9",
    name: "Hair Care",
    slug: "hair-care",
    description: "Herbal oils and powders for scalp nourishment, hair strength, and traditional hair care routines.",
    icon: "Sparkles",
    image: "/productimages/mahabhringraj_oil.jpeg",
    tips: [
      "Oil the scalp regularly before washing",
      "Use mild herbal cleansers",
      "Avoid excessive heat styling",
      "Support hair health with balanced nutrition",
      "Patch test new topical products",
    ],
    color: "#004526",
  },
  {
    id: "con-10",
    name: "Skin Care",
    slug: "skin-care",
    description: "Natural powders, oils, and face-care products for cleansing, brightening, and everyday skin wellness.",
    icon: "Sparkles",
    image: "/productimages/Multani_mitti_facepack.jpeg",
    tips: [
      "Patch test face packs and oils",
      "Cleanse gently after outdoor exposure",
      "Stay hydrated",
      "Avoid harsh scrubbing on irritated skin",
      "Use sunscreen during the day",
    ],
    color: "#C9A961",
  },
  {
    id: "con-11",
    name: "Stress Relief",
    slug: "stress-relief",
    description: "Calming herbs and oils traditionally used to support rest, resilience, and a steadier daily rhythm.",
    icon: "Brain",
    image: "/productimages/Ashwagandha_kashaye.jpeg",
    tips: [
      "Keep a consistent bedtime",
      "Practice slow breathing for five minutes",
      "Reduce stimulants late in the day",
      "Add light stretching to evenings",
      "Seek medical help for severe anxiety or insomnia",
    ],
    color: "#1F5D3B",
  },
  {
    id: "con-12",
    name: "Weight Management",
    slug: "weight-management",
    description: "Metabolism and lifestyle support with classical digestive, stamina, and wellness formulations.",
    icon: "Scale",
    image: "/productimages/active_energy.jpeg",
    tips: [
      "Eat at regular times",
      "Walk after meals when possible",
      "Prioritize protein and fiber",
      "Avoid late-night snacking",
      "Use supplements alongside diet and exercise",
    ],
    color: "#2D6A47",
  },
  {
    id: "con-13",
    name: "Women's Health",
    slug: "womens-health",
    description: "Ayurvedic support for vitality, strength, skin, digestion, and women's everyday wellness needs.",
    icon: "Flower2",
    image: "/productimages/hercordial_syrup.jpeg",
    tips: [
      "Maintain iron-rich and balanced meals",
      "Support rest during high-stress phases",
      "Track recurring symptoms",
      "Hydrate well",
      "Consult a doctor for hormonal or menstrual concerns",
    ],
    color: "#C9A961",
  },
  {
    id: "con-14",
    name: "Kid Wellness",
    slug: "kid-wellness",
    description: "Gentle wellness products selected for children's digestion, immunity, strength, and daily care.",
    icon: "Baby",
    image: "/productimages/Bed_wet_go.jpeg",
    tips: [
      "Use age-appropriate dosage only",
      "Keep meals simple and regular",
      "Encourage outdoor play",
      "Maintain sleep routines",
      "Consult a pediatrician before long-term use",
    ],
    color: "#1F5D3B",
  },
];

export function getConcernBySlug(slug: string): Concern | undefined {
  return concerns.find((c) => c.slug === slug);
}
