export interface Product {
  id: string;
  name: string;
  slug: string;
  category: string;
  categorySlug: string;
  price: number;
  originalPrice: number;
  rating: number;
  reviews: number;
  description: string;
  shortDescription: string;
  ingredients: string[];
  benefits: string[];
  usage: string;
  image: string;
  images: string[];
  concerns: string[];
  inStock: boolean;
  featured: boolean;
  badge?: string;
}

export const products: Product[] = [
  // === CHURNA ===
  {
    id: "churna-001",
    name: "Triphala Churna",
    slug: "triphala-churna",
    category: "Churna",
    categorySlug: "churna",
    price: 299,
    originalPrice: 399,
    rating: 4.5,
    reviews: 245,
    description: "A classical Ayurvedic formulation made from three potent fruits — Amla, Haritaki, and Bibhitaki. This time-tested remedy supports digestive health, detoxification, and overall rejuvenation. Our Triphala Churna is prepared using traditional methods to preserve the natural potency of each ingredient.",
    shortDescription: "Classical digestive tonic with three powerful fruits for complete gut wellness.",
    ingredients: ["Amla (Emblica officinalis)", "Haritaki (Terminalia chebula)", "Bibhitaki (Terminalia bellirica)"],
    benefits: ["Improves digestion and metabolism", "Natural detoxification", "Supports healthy weight management", "Boosts immunity", "Rich in antioxidants"],
    usage: "Mix 1-2 teaspoons with warm water before bedtime. Can also be taken with honey for better absorption.",
    image: "https://images.unsplash.com/photo-1611241893603-3c359704e0ee?w=600&h=600&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1611241893603-3c359704e0ee?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600&h=600&fit=crop",
    ],
    concerns: ["digestive-care", "immunity-booster"],
    inStock: true,
    featured: true,
    badge: "Bestseller",
  },
  {
    id: "churna-002",
    name: "Ashwagandha Churna",
    slug: "ashwagandha-churna",
    category: "Churna",
    categorySlug: "churna",
    price: 349,
    originalPrice: 449,
    rating: 4.7,
    reviews: 312,
    description: "Premium quality Ashwagandha root powder known as the 'King of Herbs' in Ayurveda. This adaptogenic herb helps the body manage stress, promotes vitality, and supports overall well-being.",
    shortDescription: "King of herbs for stress relief, vitality, and strength.",
    ingredients: ["Ashwagandha root (Withania somnifera)"],
    benefits: ["Reduces stress and anxiety", "Boosts energy and stamina", "Supports muscle strength", "Improves sleep quality", "Enhances cognitive function"],
    usage: "Take 1 teaspoon with warm milk at bedtime. Add honey or ghee for enhanced benefits.",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&h=600&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1611241893603-3c359704e0ee?w=600&h=600&fit=crop",
    ],
    concerns: ["mens-health", "immunity-booster", "pain-relief"],
    inStock: true,
    featured: true,
    badge: "Popular",
  },
  {
    id: "churna-003",
    name: "Amla Churna",
    slug: "amla-churna",
    category: "Churna",
    categorySlug: "churna",
    price: 199,
    originalPrice: 299,
    rating: 4.3,
    reviews: 189,
    description: "Pure Amla (Indian Gooseberry) powder, one of the richest natural sources of Vitamin C. Supports immunity, promotes healthy skin and hair, and aids in digestion.",
    shortDescription: "Nature's richest source of Vitamin C for immunity and vitality.",
    ingredients: ["Amla fruit (Emblica officinalis)"],
    benefits: ["Rich in Vitamin C", "Boosts immunity", "Improves hair health", "Supports skin radiance", "Aids digestion"],
    usage: "Mix 1 teaspoon with water, juice, or smoothie. Take twice daily.",
    image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600&h=600&fit=crop"],
    concerns: ["immunity-booster"],
    inStock: true,
    featured: false,
  },
  {
    id: "churna-004",
    name: "Soft Bowel Churna",
    slug: "soft-bowel-churna",
    category: "Churna",
    categorySlug: "churna",
    price: 249,
    originalPrice: 349,
    rating: 4.4,
    reviews: 156,
    description: "A gentle yet effective herbal formulation for healthy bowel movements. Combines soothing herbs that support natural digestive rhythm without dependency.",
    shortDescription: "Gentle herbal formula for comfortable, regular bowel movements.",
    ingredients: ["Saunf (Fennel)", "Ajwain (Carom seeds)", "Haritaki", "Senna leaf", "Isabgol"],
    benefits: ["Relieves constipation naturally", "Gentle on stomach", "No dependency", "Supports regularity", "Reduces bloating"],
    usage: "Take 1 teaspoon with warm water before bedtime.",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&h=600&fit=crop"],
    concerns: ["digestive-care"],
    inStock: true,
    featured: false,
  },
  // === PAK ===
  {
    id: "pak-001",
    name: "Chyawanprash Avaleha",
    slug: "chyawanprash-avaleha",
    category: "Pak",
    categorySlug: "pak",
    price: 449,
    originalPrice: 599,
    rating: 4.8,
    reviews: 423,
    description: "A premium Chyawanprash prepared with over 40 herbs, spices, and Amla base. This ancient superfood is the ultimate immunity booster, providing year-round protection and vitality.",
    shortDescription: "Ancient superfood with 40+ herbs for complete immunity and vitality.",
    ingredients: ["Amla", "Ashwagandha", "Pippali", "Shatavari", "Ghee", "Honey", "40+ herbs and spices"],
    benefits: ["Strengthens immunity", "Improves respiratory health", "Boosts energy and stamina", "Anti-aging properties", "Nourishes all body tissues"],
    usage: "Take 1-2 teaspoons daily with warm milk. Best consumed in the morning.",
    image: "https://images.unsplash.com/photo-1574226516831-e1dff420e562?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1574226516831-e1dff420e562?w=600&h=600&fit=crop"],
    concerns: ["immunity-booster"],
    inStock: true,
    featured: true,
    badge: "Premium",
  },
  {
    id: "pak-002",
    name: "Musli Pak",
    slug: "musli-pak",
    category: "Pak",
    categorySlug: "pak",
    price: 599,
    originalPrice: 799,
    rating: 4.6,
    reviews: 198,
    description: "A traditional strength and vitality tonic prepared with Safed Musli and rejuvenating herbs. Known to enhance physical stamina and overall masculine wellness.",
    shortDescription: "Traditional vitality tonic for strength and masculine wellness.",
    ingredients: ["Safed Musli", "Ashwagandha", "Shatavari", "Gokshura", "Ghee", "Sugar"],
    benefits: ["Enhances strength and stamina", "Supports reproductive health", "Boosts energy levels", "Rejuvenating properties", "Improves vitality"],
    usage: "Take 1-2 teaspoons with warm milk twice daily.",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&h=600&fit=crop"],
    concerns: ["mens-health"],
    inStock: true,
    featured: false,
  },
  // === CAPSULES ===
  {
    id: "cap-001",
    name: "Ashwagandha KSM-66 Capsules",
    slug: "ashwagandha-ksm66-capsules",
    category: "Capsules",
    categorySlug: "capsules",
    price: 499,
    originalPrice: 699,
    rating: 4.8,
    reviews: 567,
    description: "Clinically studied KSM-66 Ashwagandha root extract in easy-to-take capsules. The world's best Ashwagandha for stress relief, enhanced performance, and overall vitality.",
    shortDescription: "Clinically proven KSM-66 extract for peak stress relief and performance.",
    ingredients: ["KSM-66 Ashwagandha extract (600mg)", "Vegetable cellulose capsule"],
    benefits: ["Clinically proven stress relief", "Enhances athletic performance", "Supports cognitive function", "Improves sleep quality", "Boosts testosterone naturally"],
    usage: "Take 1 capsule twice daily with water after meals.",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop"],
    concerns: ["mens-health", "immunity-booster"],
    inStock: true,
    featured: true,
    badge: "Top Rated",
  },
  {
    id: "cap-002",
    name: "Brahmi Mind Capsules",
    slug: "brahmi-mind-capsules",
    category: "Capsules",
    categorySlug: "capsules",
    price: 399,
    originalPrice: 549,
    rating: 4.5,
    reviews: 234,
    description: "Brain tonic capsules with pure Brahmi extract for enhanced memory, focus, and cognitive clarity. Used for centuries as Ayurveda's premier brain supplement.",
    shortDescription: "Ayurveda's premier brain tonic for memory, focus, and clarity.",
    ingredients: ["Brahmi extract (Bacopa monnieri, 500mg)", "Shankhpushpi extract", "Vegetable capsule"],
    benefits: ["Enhances memory and recall", "Improves concentration", "Reduces mental fatigue", "Supports nervous system", "Calms the mind"],
    usage: "Take 1 capsule twice daily with water.",
    image: "https://images.unsplash.com/photo-1559757175-7cb057fba93c?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1559757175-7cb057fba93c?w=600&h=600&fit=crop"],
    concerns: ["immunity-booster"],
    inStock: true,
    featured: false,
  },
  {
    id: "cap-003",
    name: "Triphala Guggul Capsules",
    slug: "triphala-guggul-capsules",
    category: "Capsules",
    categorySlug: "capsules",
    price: 349,
    originalPrice: 499,
    rating: 4.4,
    reviews: 178,
    description: "Powerful combination of Triphala and Guggul for comprehensive digestive and metabolic support. Helps maintain healthy cholesterol levels and supports weight management.",
    shortDescription: "Triphala meets Guggul for digestive and metabolic excellence.",
    ingredients: ["Triphala extract", "Guggul resin (Commiphora mukul)", "Pippali"],
    benefits: ["Supports healthy metabolism", "Aids weight management", "Improves digestion", "Helps maintain cholesterol levels", "Detoxification support"],
    usage: "Take 2 capsules twice daily with warm water after meals.",
    image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=600&h=600&fit=crop"],
    concerns: ["digestive-care", "cardiac-care"],
    inStock: true,
    featured: false,
  },
  // === OILS ===
  {
    id: "oil-001",
    name: "Bhringraj Hair Oil",
    slug: "bhringraj-hair-oil",
    category: "Oils",
    categorySlug: "oils",
    price: 349,
    originalPrice: 449,
    rating: 4.6,
    reviews: 389,
    description: "Traditional Ayurvedic hair oil infused with Bhringraj, Amla, and Brahmi. Nourishes scalp, strengthens hair roots, and promotes natural hair growth.",
    shortDescription: "Ayurvedic hair elixir for stronger, thicker, and lustrous hair.",
    ingredients: ["Bhringraj oil", "Amla oil", "Brahmi oil", "Coconut oil base", "Neem extract"],
    benefits: ["Promotes hair growth", "Reduces hair fall", "Prevents premature greying", "Nourishes scalp", "Adds shine and lustre"],
    usage: "Warm oil slightly. Massage into scalp and hair. Leave for 1-2 hours or overnight. Wash with mild shampoo.",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop"],
    concerns: ["mens-health"],
    inStock: true,
    featured: true,
  },
  {
    id: "oil-002",
    name: "Mahanarayan Tail",
    slug: "mahanarayan-tail",
    category: "Oils",
    categorySlug: "oils",
    price: 399,
    originalPrice: 549,
    rating: 4.7,
    reviews: 267,
    description: "Classical Ayurvedic therapeutic oil for joint and muscle pain relief. Made with 30+ herbs in sesame oil base, this potent oil provides deep relief from body aches.",
    shortDescription: "30+ herb therapeutic oil for deep joint and muscle relief.",
    ingredients: ["Sesame oil base", "Ashwagandha", "Shatavari", "Bala", "Dashmool", "30+ traditional herbs"],
    benefits: ["Relieves joint pain", "Reduces muscle stiffness", "Improves flexibility", "Soothes inflammation", "Nourishes bones and joints"],
    usage: "Warm oil. Apply to affected area and massage gently for 10-15 minutes. Use daily for best results.",
    image: "https://images.unsplash.com/photo-1600428877878-1a0ff561972c?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1600428877878-1a0ff561972c?w=600&h=600&fit=crop"],
    concerns: ["pain-relief"],
    inStock: true,
    featured: false,
  },
  // === POWDERS ===
  {
    id: "pow-001",
    name: "Moringa Leaf Powder",
    slug: "moringa-leaf-powder",
    category: "Powders",
    categorySlug: "powders",
    price: 279,
    originalPrice: 399,
    rating: 4.5,
    reviews: 201,
    description: "Pure, organic Moringa leaf powder — nature's multivitamin. Packed with vitamins, minerals, and antioxidants, it supports overall nutrition and vitality.",
    shortDescription: "Nature's multivitamin — packed with essential vitamins and minerals.",
    ingredients: ["Moringa oleifera leaf powder (100% pure)"],
    benefits: ["Rich in vitamins A, C, E", "High in iron and calcium", "Powerful antioxidant", "Supports energy levels", "Anti-inflammatory properties"],
    usage: "Add 1 teaspoon to smoothies, juices, or warm water. Take twice daily.",
    image: "https://images.unsplash.com/photo-1622467827417-bbe2237067a9?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1622467827417-bbe2237067a9?w=600&h=600&fit=crop"],
    concerns: ["immunity-booster"],
    inStock: true,
    featured: false,
  },
  {
    id: "pow-002",
    name: "Turmeric Gold Powder",
    slug: "turmeric-gold-powder",
    category: "Powders",
    categorySlug: "powders",
    price: 199,
    originalPrice: 299,
    rating: 4.4,
    reviews: 345,
    description: "High-curcumin turmeric powder with enhanced bioavailability. The golden spice of Ayurveda, known for its powerful anti-inflammatory and healing properties.",
    shortDescription: "High-curcumin golden turmeric for inflammation and healing.",
    ingredients: ["Turmeric root powder (Curcuma longa)", "Black pepper extract (for bioavailability)"],
    benefits: ["Powerful anti-inflammatory", "Strong antioxidant", "Supports joint health", "Boosts immunity", "Promotes healthy skin"],
    usage: "Mix 1/2 teaspoon with warm milk (golden milk) or add to food. Take daily.",
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&h=600&fit=crop"],
    concerns: ["pain-relief", "immunity-booster"],
    inStock: true,
    featured: true,
  },
  // === JUICES ===
  {
    id: "juice-001",
    name: "Amla Juice",
    slug: "amla-juice",
    category: "Juices",
    categorySlug: "juices",
    price: 249,
    originalPrice: 349,
    rating: 4.3,
    reviews: 178,
    description: "Fresh cold-pressed Amla juice, the richest natural source of Vitamin C. Supports immunity, improves digestion, and promotes youthful skin and healthy hair.",
    shortDescription: "Cold-pressed Vitamin C powerhouse for immunity and radiance.",
    ingredients: ["Fresh Amla juice (100% pure)", "No added sugar", "No preservatives"],
    benefits: ["Highest natural Vitamin C source", "Boosts immunity", "Improves skin health", "Supports hair growth", "Alkalizes the body"],
    usage: "Take 20-30ml with equal amount of water on empty stomach. Twice daily.",
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&h=600&fit=crop"],
    concerns: ["immunity-booster"],
    inStock: true,
    featured: false,
  },
  {
    id: "juice-002",
    name: "Aloe Vera Juice",
    slug: "aloe-vera-juice",
    category: "Juices",
    categorySlug: "juices",
    price: 299,
    originalPrice: 399,
    rating: 4.2,
    reviews: 145,
    description: "Pure Aloe Vera juice for digestive wellness and detoxification. This cooling tonic soothes the gut, hydrates the body, and supports clear skin.",
    shortDescription: "Cooling digestive tonic for gut health and clear skin.",
    ingredients: ["Aloe Vera leaf juice (Aloe barbadensis)", "No artificial preservatives"],
    benefits: ["Soothes digestive tract", "Detoxifies the body", "Supports clear skin", "Hydrating and cooling", "Boosts metabolism"],
    usage: "Take 20-30ml with water before breakfast. Shake well before use.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=600&fit=crop"],
    concerns: ["digestive-care"],
    inStock: true,
    featured: false,
  },
  {
    id: "juice-003",
    name: "Karela Jamun Juice",
    slug: "karela-jamun-juice",
    category: "Juices",
    categorySlug: "juices",
    price: 279,
    originalPrice: 399,
    rating: 4.5,
    reviews: 234,
    description: "A potent combination of Bitter Gourd (Karela) and Indian Blackberry (Jamun) for maintaining healthy blood sugar levels. This Ayurvedic tonic supports pancreatic health naturally.",
    shortDescription: "Natural blood sugar management with Karela and Jamun power.",
    ingredients: ["Karela (Bitter gourd) juice", "Jamun (Indian Blackberry) juice"],
    benefits: ["Supports healthy blood sugar", "Improves insulin sensitivity", "Rich in antioxidants", "Supports pancreatic health", "Aids in metabolism"],
    usage: "Take 20-30ml with water before meals. Twice daily for best results.",
    image: "https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=600&h=600&fit=crop"],
    concerns: ["diabetic-care"],
    inStock: true,
    featured: true,
    badge: "Recommended",
  },
  // === SYRUPS ===
  {
    id: "syrup-001",
    name: "Dashmularishta",
    slug: "dashmularishta",
    category: "Syrups",
    categorySlug: "syrups",
    price: 199,
    originalPrice: 279,
    rating: 4.4,
    reviews: 267,
    description: "Classical Ayurvedic tonic prepared with ten roots (Dashmool). Supports post-natal recovery, strengthens the body, and boosts overall vitality.",
    shortDescription: "Classical ten-root tonic for strength and post-natal recovery.",
    ingredients: ["Dashmool (10 root extracts)", "Jaggery", "Dhataki flower", "Natural fermentation"],
    benefits: ["Post-natal rejuvenation", "Boosts strength", "Reduces weakness", "Supports reproductive health", "Anti-inflammatory"],
    usage: "Take 15-20ml with equal amount of water after meals. Twice daily.",
    image: "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1471943311424-646960669fbc?w=600&h=600&fit=crop"],
    concerns: ["immunity-booster", "pain-relief"],
    inStock: true,
    featured: false,
  },
  {
    id: "syrup-002",
    name: "Lohasava",
    slug: "lohasava",
    category: "Syrups",
    categorySlug: "syrups",
    price: 229,
    originalPrice: 329,
    rating: 4.3,
    reviews: 123,
    description: "Iron-rich Ayurvedic syrup for managing anemia and iron deficiency naturally. This traditional formulation improves hemoglobin levels and supports overall blood health.",
    shortDescription: "Natural iron-rich tonic for anemia and blood health.",
    ingredients: ["Loha Bhasma (Iron)", "Triphala", "Trikatu", "Jaggery", "Honey"],
    benefits: ["Improves hemoglobin levels", "Treats iron deficiency", "Boosts energy", "Supports liver health", "Enhances blood circulation"],
    usage: "Take 15-20ml with equal amount of water after meals.",
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&h=600&fit=crop"],
    concerns: ["immunity-booster"],
    inStock: true,
    featured: false,
  },
  {
    id: "syrup-003",
    name: "Arjunarishta",
    slug: "arjunarishta",
    category: "Syrups",
    categorySlug: "syrups",
    price: 249,
    originalPrice: 349,
    rating: 4.6,
    reviews: 189,
    description: "Heart-health tonic prepared with Arjuna bark. This classical Ayurvedic formulation supports cardiovascular health, maintains healthy blood pressure, and strengthens the heart muscles.",
    shortDescription: "Arjuna bark tonic for heart health and blood pressure support.",
    ingredients: ["Arjuna bark extract", "Draksha (Grape)", "Mahua flower", "Jaggery"],
    benefits: ["Supports heart health", "Maintains blood pressure", "Strengthens heart muscles", "Reduces cholesterol", "Antioxidant protection"],
    usage: "Take 15-20ml with equal amount of water after meals. Twice daily.",
    image: "https://images.unsplash.com/photo-1544991875-5dc1b05f607d?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1544991875-5dc1b05f607d?w=600&h=600&fit=crop"],
    concerns: ["cardiac-care"],
    inStock: true,
    featured: true,
  },
  // Additional products for variety
  {
    id: "oil-003",
    name: "Kshirbala Tail",
    slug: "kshirbala-tail",
    category: "Oils",
    categorySlug: "oils",
    price: 349,
    originalPrice: 499,
    rating: 4.5,
    reviews: 156,
    description: "A premium Ayurvedic medicated oil prepared with milk and Bala herb. Excellent for neurological and musculoskeletal health, providing deep nourishment to nerves and tissues.",
    shortDescription: "Premium medicated oil for neurological and musculoskeletal health.",
    ingredients: ["Bala (Sida cordifolia)", "Cow milk", "Sesame oil", "Traditional herbs"],
    benefits: ["Supports nerve health", "Relieves muscular pain", "Nourishes tissues", "Improves flexibility", "Anti-inflammatory"],
    usage: "Warm gently and massage on affected areas. Use daily for optimal results.",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop"],
    concerns: ["pain-relief"],
    inStock: true,
    featured: false,
  },
  {
    id: "cap-004",
    name: "Arjuna Heart Guard",
    slug: "arjuna-heart-guard",
    category: "Capsules",
    categorySlug: "capsules",
    price: 449,
    originalPrice: 599,
    rating: 4.7,
    reviews: 213,
    description: "Concentrated Arjuna bark extract capsules for comprehensive cardiac support. Clinically researched for maintaining healthy heart function and blood pressure.",
    shortDescription: "Concentrated Arjuna for comprehensive cardiac protection.",
    ingredients: ["Arjuna bark extract (500mg)", "Vegetable capsule"],
    benefits: ["Supports cardiovascular health", "Maintains blood pressure", "Strengthens heart muscle", "Rich in antioxidants", "Supports healthy cholesterol"],
    usage: "Take 1 capsule twice daily with water after meals.",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop"],
    concerns: ["cardiac-care"],
    inStock: true,
    featured: false,
  },
  {
    id: "pow-003",
    name: "Diabetic Care Powder",
    slug: "diabetic-care-powder",
    category: "Powders",
    categorySlug: "powders",
    price: 399,
    originalPrice: 549,
    rating: 4.6,
    reviews: 287,
    description: "A scientifically formulated blend of blood sugar-regulating herbs like Karela, Jamun, Neem, and Gurmar. This potent herbal combination supports healthy glucose metabolism.",
    shortDescription: "Multi-herb formula for natural blood sugar management.",
    ingredients: ["Karela (Bitter gourd)", "Jamun seed", "Neem leaf", "Gurmar (Gymnema sylvestre)", "Methi (Fenugreek)"],
    benefits: ["Supports healthy blood sugar", "Improves insulin function", "Reduces sugar cravings", "Supports pancreatic health", "Rich in antioxidants"],
    usage: "Take 1 teaspoon with warm water before meals. Twice daily.",
    image: "https://images.unsplash.com/photo-1622467827417-bbe2237067a9?w=600&h=600&fit=crop",
    images: ["https://images.unsplash.com/photo-1622467827417-bbe2237067a9?w=600&h=600&fit=crop"],
    concerns: ["diabetic-care"],
    inStock: true,
    featured: true,
    badge: "Doctor Pick",
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug);
}

export function getProductsByConcern(concernSlug: string): Product[] {
  return products.filter((p) => p.concerns.includes(concernSlug));
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getRelatedProducts(product: Product, limit: number = 4): Product[] {
  return products
    .filter(
      (p) =>
        p.id !== product.id &&
        (p.categorySlug === product.categorySlug ||
          p.concerns.some((c) => product.concerns.includes(c)))
    )
    .slice(0, limit);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.shortDescription.toLowerCase().includes(q)
  );
}
