update public.products_by_category set images = ARRAY['/productimages/pachanrattan_syrup.jpeg'] where "Product Name" = 'Pachanrattan Syrup';
update public.products_by_category set images = ARRAY['/productimages/active_energy.jpeg'] where "Product Name" = 'Active Energy Syrup';
update public.products_by_category set images = ARRAY['/productimages/Ayurpure_syrup.jpeg'] where "Product Name" = 'Ayurpure';
update public.products_by_category set images = ARRAY['/productimages/Yakirattan.jpeg'] where "Product Name" = 'Yakritrattan';
update public.products_by_category set images = ARRAY['/productimages/KuffRattan_syrup.jpeg'] where "Product Name" = 'Kuff Ratan';
update public.products_by_category set images = ARRAY['/productimages/Bed_wet_go.jpeg'] where "Product Name" = 'Bed Wet Go';
update public.products_by_category set images = ARRAY['/productimages/Kutajcare_syrup.jpeg'] where "Product Name" = 'Kutaj Cure';
update public.products_by_category set images = ARRAY['/productimages/BrahmiAmrita_syrup.jpeg'] where "Product Name" = 'Shankh Pushpi';
update public.products_by_category set images = ARRAY['/productimages/kastone-AB.jpeg'] where "Product Name" = 'Kastone';
update public.products_by_category set images = ARRAY['/productimages/uric_acid.jpeg'] where "Product Name" = 'Uric Acid Syrup';
update public.products_by_category set images = ARRAY['/productimages/Laxure_syrup.jpeg'] where "Product Name" = 'Laxure Kids Syrup';
update public.products_by_category set images = ARRAY['/productimages/Gulab_ARQ.jpeg'] where "Product Name" = 'Gulab Arq';
update public.products_by_category set images = ARRAY['/productimages/ARQ_Purnarnava.jpeg'] where "Product Name" = 'Punarnava Arq';
update public.products_by_category set images = ARRAY['/productimages/Makoy_Arq.jpeg'] where "Product Name" = 'Makoy Arq';
update public.products_by_category set images = ARRAY['/productimages/Arq_kashni.jpeg'] where "Product Name" = 'Khasni Arq';
update public.products_by_category set images = ARRAY['/productimages/saunf_arq.jpeg'] where "Product Name" = 'Saunf Arq';
update public.products_by_category set images = ARRAY['/productimages/joshanda.jpeg'] where "Product Name" = 'Joshanda Syrup';
update public.products_by_category set images = ARRAY['/productimages/hercordial_syrup.jpeg'] where "Product Name" = 'Female Cordial';
update public.products_by_category set images = ARRAY['/productimages/Bed_wet_go.jpeg'] where "Product Name" = 'Chawarka Kids';
update public.products_by_category set images = ARRAY['/productimages/Laxure_syrup.jpeg'] where "Product Name" = 'Laxure Adult';
update public.products_by_category set images = ARRAY['/productimages/active_energy.jpeg'] where "Product Name" = 'Balya Rattan Syrup';
update public.products_by_category set images = ARRAY['/productimages/amla_powder.jpeg'] where "Product Name" = 'Amla Powder';
update public.products_by_category set images = ARRAY['/productimages/amla_reetha.jpeg'] where "Product Name" = 'Amla Reetha Shikakai';
update public.products_by_category set images = ARRAY['/productimages/Hibiscus_powder.jpeg'] where "Product Name" = 'Hibiscus Powder';
update public.products_by_category set images = ARRAY['/productimages/moringa_powder.jpeg'] where "Product Name" = 'Moringa Powder';
update public.products_by_category set images = ARRAY['/productimages/ArjunChal_powder.jpeg'] where "Product Name" = 'Arjun Chaal';
update public.products_by_category set images = ARRAY['/productimages/Bhringraj_powder.jpeg'] where "Product Name" = 'Bhringraj Powder';
update public.products_by_category set images = ARRAY['/productimages/Derma_care_powder.jpeg'] where "Product Name" = 'Derma Care Powder';
update public.products_by_category set images = ARRAY['/productimages/gokhru_powder.jpeg'] where "Product Name" = 'Gokhru Powder';
update public.products_by_category set images = ARRAY['/productimages/indigo_powder.jpeg'] where "Product Name" = 'Indigo Powder';
update public.products_by_category set images = ARRAY['/productimages/kaunch_beej.jpeg'] where "Product Name" = 'Kaunch Beej Powder';
update public.products_by_category set images = ARRAY['/productimages/Multani_mitti_facepack.jpeg'] where "Product Name" = 'Orange Peel Powder';
update public.products_by_category set images = ARRAY['/productimages/Ashwagandha_kashaye.jpeg'] where "Product Name" = 'Ashwagandha Powder';
update public.products_by_category set images = ARRAY['/productimages/moringa_powder.jpeg'] where "Product Name" = 'Neem Powder';
update public.products_by_category set images = ARRAY['/productimages/Shatawari_Powder.jpeg'] where "Product Name" = 'Shatavari Powder';
update public.products_by_category set images = ARRAY['/productimages/Multani_mitti_facepack.jpeg'] where "Product Name" = 'Multani Mitti';
update public.products_by_category set images = ARRAY['/productimages/karela_kashaye.jpeg'] where "Product Name" = 'Neem Karela Jamun Powder';
update public.products_by_category set images = ARRAY['/productimages/moringa_powder.jpeg'] where "Product Name" = 'Mulethi Powder';
update public.products_by_category set images = ARRAY['/productimages/Haridra_khand.jpeg'] where "Product Name" = 'Amba Haldi Powder';
update public.products_by_category set images = ARRAY['/productimages/Ashwagandha_kashaye.jpeg'] where "Product Name" = 'Ashwagandha Capsule';
update public.products_by_category set images = ARRAY['/productimages/Haridra_khand.jpeg'] where "Product Name" = 'Haridra Capsule';
update public.products_by_category set images = ARRAY['/productimages/Arjuna_kashaye.jpeg'] where "Product Name" = 'Arjuna Capsule';
update public.products_by_category set images = ARRAY['/productimages/Shatawari_Powder.jpeg'] where "Product Name" = 'Shatavari Capsule';
update public.products_by_category set images = ARRAY['/productimages/Amla_kashaye%27.jpeg'] where "Product Name" = 'Amla Capsule';
update public.products_by_category set images = ARRAY['/productimages/Arshar7_capsule.jpeg'] where "Product Name" = 'Shilajit Capsule';
update public.products_by_category set images = ARRAY['/productimages/amla_powder.jpeg'] where "Product Name" = 'Trifla Capsule';
update public.products_by_category set images = ARRAY['/productimages/Arshar7_capsule.jpeg'] where "Product Name" = 'Hadjod Capsule';
update public.products_by_category set images = ARRAY['/productimages/karela_kashaye.jpeg'] where "Product Name" = 'Neem Capsule';
update public.products_by_category set images = ARRAY['/productimages/gokhru_powder.jpeg'] where "Product Name" = 'Gokhru Capsule';
update public.products_by_category set images = ARRAY['/productimages/mahabhringraj_oil.jpeg'] where "Product Name" = 'Bhringraj Oil';
update public.products_by_category set images = ARRAY['/productimages/hair_oil.jpeg'] where "Product Name" = 'Onion Oil';
update public.products_by_category set images = ARRAY['/productimages/hair_oil.jpeg'] where "Product Name" = 'Badam rogan Oil';
update public.products_by_category set images = ARRAY['/productimages/Clove_oil.jpeg'] where "Product Name" = 'Garlic Oil';
update public.products_by_category set images = ARRAY['/productimages/Lin_seed_oil.jpeg'] where "Product Name" = 'Walnut Oil';
update public.products_by_category set images = ARRAY['/productimages/malkangni_oil.jpeg'] where "Product Name" = 'Malkangni Oil';
update public.products_by_category set images = ARRAY['/productimages/kalonji_oil.jpeg'] where "Product Name" = 'Kalounji Oil';
update public.products_by_category set images = ARRAY['/images/coming-soon.svg'] where "Product Name" = 'Rosemary Oil';
update public.products_by_category set images = ARRAY['/productimages/indica_seed_oil.jpeg'] where "Product Name" = 'Neem Oil';
update public.products_by_category set images = ARRAY['/productimages/Castor_oil.jpeg'] where "Product Name" = 'Castor Oil';
update public.products_by_category set images = ARRAY['/productimages/lowki_oil.jpeg'] where "Product Name" = 'Lawki Oil';
update public.products_by_category set images = ARRAY['/productimages/amla_powder.jpeg'] where "Product Name" = 'Amla Juice';
update public.products_by_category set images = ARRAY['/productimages/karela_kashaye.jpeg'] where "Product Name" = 'Karela Jamun Juice';
update public.products_by_category set images = ARRAY['/productimages/Aloevera_sawaras.jpeg'] where "Product Name" = 'Aloe Vera Juice';
update public.products_by_category set images = ARRAY['/productimages/giloy_kashaye.jpeg'] where "Product Name" = 'Giloy Juice';
update public.products_by_category set images = ARRAY['/productimages/Badam_pak.jpeg'] where "Product Name" = 'Supari Pak';
update public.products_by_category set images = ARRAY['/productimages/Badam_pak.jpeg'] where "Product Name" = 'Salam Pak';
update public.products_by_category set images = ARRAY['/productimages/moosli_pak.jpeg'] where "Product Name" = 'Moosli Pak';
update public.products_by_category set images = ARRAY['/productimages/Konch_pak.jpeg'] where "Product Name" = 'Konch Pak';
update public.products_by_category set images = ARRAY['/productimages/Ashwagandha_pak.jpeg'] where "Product Name" = 'Ashwagandha Pak';
update public.products_by_category set images = ARRAY['/productimages/Badam_pak.jpeg'] where "Product Name" = 'Badam Pak';
update public.products_by_category set images = ARRAY['/productimages/soft_Bowl_Churan.jpeg'] where "Product Name" = 'Soft Bowl';
update public.products_by_category set images = ARRAY['/productimages/Madhunashneem_churan.jpeg'] where "Product Name" = 'Madhunashneem';
update public.products_by_category set images = ARRAY['/productimages/amla_powder.jpeg'] where "Product Name" = 'Amla Churna';
update public.products_by_category set images = ARRAY['/productimages/Bhumi_amla_churan.jpeg'] where "Product Name" = 'Triphla Churna';
update public.products_by_category set images = ARRAY['/productimages/moringa_powder.jpeg'] where "Product Name" = 'Panchtrimool';
update public.products_by_category set images = ARRAY['/productimages/soft_Bowl_Churan.jpeg'] where "Product Name" = 'Soft Bowl Junior';
