delete from public.products_by_concern
where "Concern" in (
  'Immunity Booster',
  'Pain Relief',
  'Men''s Health',
  'Cardiac Care',
  'Cough & Cold Relief',
  'Digestive Care',
  'Diabetic Care',
  'Elderly Care',
  'Hair Care',
  'Stress Relief',
  'Weight Management',
  'Women''s Health',
  'Skin Care',
  'Kid Wellness'
);

with concern_seed ("Product Name","Concern","Quantity","Price") as (
  values
  ('Immunerattan Syrup','Immunity Booster',null,null),
  ('Amla Powder','Immunity Booster',null,null),
  ('Amla Churna','Immunity Booster',null,null),
  ('Giloy Juice','Immunity Booster',null,null),
  ('Ashwagandha Powder','Immunity Booster',null,null),
  ('Ashwagandha Capsule','Immunity Booster',null,null),
  ('Joshanda Syrup','Immunity Booster',null,null),
  ('Aloe Vera Juice','Immunity Booster','250ml',null),
  ('Shankh Pushpi','Immunity Booster',null,null),

  ('Arthofit Oil','Pain Relief',null,null),
  ('Methi Oil','Pain Relief','60ml',160),
  ('Lawki Oil','Pain Relief','100ml',120),
  ('Hadjod Capsule','Pain Relief','60 capsules',280),
  ('Garlic Oil','Pain Relief','60ml',249),
  ('Walnut Oil','Pain Relief','60ml',280),
  ('Amba Haldi Powder','Pain Relief','100gm',150),
  ('Haridra Capsule','Pain Relief',null,null),
  ('Malkangni Oil','Pain Relief','60ml',120),

  ('Salam Pak','Men''s Health','100gm',350),
  ('Moosli Pak','Men''s Health',null,null),
  ('Konch Pak','Men''s Health',null,null),
  ('Ashwagandha Pak','Men''s Health',null,null),
  ('Badam Pak','Men''s Health',null,null),
  ('Ashwagandha Capsule','Men''s Health',null,null),
  ('Ashwagandha Powder','Men''s Health',null,null),
  ('Kaunch Beej Powder','Men''s Health',null,null),
  ('Shilajit Capsule','Men''s Health',null,null),
  ('Active Energy Syrup','Men''s Health',null,null),
  ('Balya Rattan Syrup','Men''s Health','200ml',150),
  ('Yakritrattan','Men''s Health',null,null),
  ('Moringa Powder','Men''s Health',null,null),
  ('Shatavari Powder','Men''s Health',null,null),
  ('Shatavari Capsule','Men''s Health',null,null),

  ('Arjuna Capsule','Cardiac Care',null,300),
  ('Arjun Chaal','Cardiac Care',null,180),
  ('Gaujawan Arq','Cardiac Care',null,150),

  ('Kuff Ratan','Cough & Cold Relief',null,null),
  ('Joshanda Syrup','Cough & Cold Relief',null,null),
  ('Immunerattan Syrup','Cough & Cold Relief',null,null),
  ('Mulethi Powder','Cough & Cold Relief',null,null),

  ('Castor Oil','Digestive Care',null,null),
  ('Pachanrattan Syrup','Digestive Care',null,null),
  ('Soft Bowl Junior','Digestive Care',null,null),
  ('Yakritrattan','Digestive Care',null,null),
  ('Chawarka Kids','Digestive Care',null,null),
  ('Triphla Churna','Digestive Care',null,null),
  ('Laxure Adult','Digestive Care',null,null),
  ('Rosemary Oil','Digestive Care','60ml',220),
  ('Hibiscus Powder','Digestive Care',null,null),
  ('Neem Oil','Digestive Care','60ml',90),
  ('Derma Care Powder','Digestive Care',null,null),
  ('Kalounji Oil','Digestive Care','60ml',140),

  ('Karela Jamun Juice','Diabetic Care','500ml',150),
  ('Madhunashneem','Diabetic Care',null,null),
  ('Neem Karela Jamun Powder','Diabetic Care',null,null),
  ('Neem Powder','Diabetic Care',null,null),
  ('Neem Capsule','Diabetic Care',null,140),

  ('Triphla Churna','Elderly Care',null,null),
  ('Soft Bowl','Elderly Care',null,null),
  ('Uric Acid Syrup','Elderly Care',null,null),
  ('Yakritrattan','Elderly Care',null,null),
  ('Kuff Ratan','Elderly Care',null,null),
  ('Arthofit Oil','Elderly Care','60ml',150),
  ('Amla Juice','Elderly Care',null,140),
  ('Castor Oil','Elderly Care','30ml',90),
  ('Lawki Oil','Elderly Care','100ml',120),
  ('Shilajit Capsule','Elderly Care',null,null),

  ('Bhringraj Oil','Hair Care','100ml',259),
  ('Onion Oil','Hair Care','150ml',120),
  ('Mahabhringraj Oil','Hair Care','100ml',210),
  ('Indigo Powder','Hair Care','100gm',70),
  ('Amla Powder','Hair Care',null,null),
  ('Amla Reetha Shikakai','Hair Care',null,null),

  ('Ashwagandha Capsule','Stress Relief',null,null),
  ('Ashwagandha Powder','Stress Relief',null,null),
  ('Ashwagandha Pak','Stress Relief',null,null),
  ('Active Energy Syrup','Stress Relief',null,null),
  ('Shankh Pushpi','Stress Relief',null,null),
  ('Kaddu Oil','Stress Relief','60ml',90),
  ('Lawki Oil','Stress Relief',null,null),
  ('Khas Khas Oil','Stress Relief','60ml',140),
  ('Badam rogan Oil','Stress Relief',null,null),

  ('Chawarka Kids','Weight Management',null,null),
  ('Active Energy Syrup','Weight Management',null,null),
  ('Yakritrattan','Weight Management',null,null),
  ('Shatavari Capsule','Weight Management',null,null),
  ('Shatavari Powder','Weight Management',null,null),
  ('Ashwagandha Capsule','Weight Management',null,null),
  ('Ashwagandha Pak','Weight Management',null,null),
  ('Ashwagandha Powder','Weight Management',null,null),

  ('Hercordial','Women''s Health',null,null),
  ('Female Cordial','Women''s Health',null,null),
  ('Ayurpure','Women''s Health',null,null),
  ('Shatavari Capsule','Women''s Health',null,null),
  ('Shatavari Powder','Women''s Health',null,null),
  ('Hibiscus Powder','Women''s Health',null,null),
  ('Amla Powder','Women''s Health',null,null),
  ('Amla Reetha Shikakai','Women''s Health',null,null),
  ('Shilajit Capsule','Women''s Health',null,null),
  ('Yakritrattan','Women''s Health',null,null),
  ('Neem Powder','Women''s Health',null,null),
  ('Ashwagandha Capsule','Women''s Health',null,null),
  ('Ashwagandha Powder','Women''s Health',null,null),
  ('Active Energy Syrup','Women''s Health',null,null),
  ('Haridra Capsule','Women''s Health',null,null),

  ('Multani Mitti','Skin Care','50gm',55),
  ('Orange Peel Powder','Skin Care','100gm',120),
  ('Derma Care Powder','Skin Care',null,null),
  ('Badam rogan Oil','Skin Care',null,null),
  ('Neem Powder','Skin Care',null,null),
  ('Neem Oil','Skin Care',null,null),

  ('Shankh Pushpi','Kid Wellness','200ml',140),
  ('Bed Wet Go','Kid Wellness','200ml',190),
  ('Laxure Kids Syrup','Kid Wellness',null,null),
  ('Ashwagandha Powder','Kid Wellness',null,null),
  ('Chawarka Kids','Kid Wellness',null,null),
  ('Yakritrattan','Kid Wellness',null,null),
  ('Ayurpure','Kid Wellness',null,null),
  ('Active Energy Syrup','Kid Wellness',null,null),
  ('Immunerattan Syrup','Kid Wellness',null,null),
  ('Joshanda Syrup','Kid Wellness',null,null),
  ('Badam rogan Oil','Kid Wellness','30ml',140),
  ('Soft Bowl Junior','Kid Wellness',null,null)
)
insert into public.products_by_concern ("Product Name","Concern","Quantity","Price","images")
select distinct
  p."Product Name",
  s."Concern",
  coalesce(s."Quantity", p."Quantity"),
  coalesce(s."Price", nullif(regexp_replace(split_part(p."Price", ',', 1), '[^0-9.]', '', 'g'), '')::numeric),
  p.images
from concern_seed s
join public.products_by_category p
  on lower(p."Product Name") = lower(s."Product Name");
